name: Test Hyper-Growth Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: List project files
        run: |
          echo "Working dir: $(pwd)"
          ls -R .
